language: python
sudo: required
dist: trusty
os: linux

python:
  - "3.5"
  - "3.6"

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.5.5
  - os: osx
    language: generic
    env: PYTHON=3.6.3

addons:
  apt:
    update: true
    packages:
      - hdf5-tools

# https://pythonhosted.org/CodeChat/.travis.yml.html
before_install:
  # - linux() { if test "$TRAVIS_OS_NAME" == "linux"; then $@; fi; }
  - osx() { if test "$TRAVIS_OS_NAME" == "osx"; then $@; fi; }
  - osx brew update
  - osx brew install gcc || true
  - osx brew link --overwrite gcc
  - osx brew install hdf5
  - osx brew install lzo
  - osx brew outdated pyenv || brew upgrade pyenv
  - osx brew install pyenv-virtualenv
  - osx pyenv install $PYTHON
  - osx export PYENV_VERSION=$PYTHON
  - osx export PATH="/Users/travis/.pyenv/shims:${PATH}"
  - osx pyenv-virtualenv venv
  - osx source venv/bin/activate
  - python --version
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install --upgrade pip
  - pip install --upgrade setuptools


install:
  - make
  - make install_test
  - make install_graph
  - make install

script:
  - babao
  - make flake
  - make lint
  - make test
